import time
print('歡迎滾進個資紀錄系統')
a=[]
while True:
    print('1.新增個資'+'\n'+'2.查詢個資'+'\n'+'3.刪除個資')
    sb=input('輸入:')
    b=[]
    if sb.isdecimal() and sb=='1':
        sb=input('輸入姓名:')
        b.append(sb)
        sb=input('輸入性別:')
        b.append(sb)
        sb=input('輸入身高:')
        b.append(sb)
        sb=input('輸入體重:')
        b.append(sb)
        sb=input('輸入年齡:')
        b.append(sb)
        print('請檢察是否正確:',b)
        print('1.對,2.錯')
        d=input('')
        while d=='2':
            sb=input('輸入姓名:')
            b.append(sb)
            sb=input('輸入性別:')
            b.append(sb)
            sb=input('輸入身高:')
            b.append(sb)
            sb=input('輸入體重:')
            b.append(sb)
            sb=input('輸入年齡:')
            b.append(sb)
            print('請檢察是否正確:',b)
            print('1.對,2.錯')
            d=input('')
        print('輸入中......')
        a.append([b])
        time.sleep(3)
        print('輸入完畢')
        print(a)
