import time as tt
import random as rr
print('大家安安')
tt.sleep(1.5)
print('(空氣正在凝結......)')
tt.sleep(1.5)
print('來玩一些小遊戲好了')
tt.sleep(1.5)
print('我來說說遊戲規則')
tt.sleep(1.5)
print('我先說一句話，你在說一句話')
tt.sleep(1.5)
print('記得，和我說的一樣，不然就要接受懲罰')
tt.sleep(1.5)
print('預備備')
tt.sleep(1)
print('開始!')
tt.sleep(1.5)
print('阿巴阿巴')
tt.sleep(1.5)
a=str(input('請輸入:'))
if a=='阿巴阿巴':
    print('過關')
    tt.sleep(1.5)
    print('作者正在高速更新，未完待續')
    tt.sleep(1.5)
    print('正在自動退出')
else:
    print('過關失敗')
    tt.sleep(1.5)
    print('處罰你汪汪兩聲')
    tt.sleep(3)
    print('作者正在高速更新，未完待續')
    tt.sleep(1.5)
    print('正在自動退出')